feat: update debootstrap to 1.0.133

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -233,6 +233,8 @@ keyring () {
 detect_container () {
 	if [ "$container" = lxc ]; then
 		CONTAINER="lxc"
+	elif [ "$container" = mmdebstrap-unshare ]; then
+		CONTAINER="mmdebstrap-unshare"
 	elif grep -qs container=lxc-libvirt /proc/1/environ; then
 		CONTAINER="lxc-libvirt"
 	elif grep -qs ^systemd-nspawn$ /run/systemd/container || grep -qs systemd-nspawn /proc/1/environ || [ "$container" = "systemd-nspawn" ]; then
@@ -242,6 +244,7 @@ detect_container () {
 	else
 		CONTAINER=""
 	fi
+	# TODO: detect sub-hurds
 }
 
 ########################################################## variant handling
@@ -978,7 +981,7 @@ extract_dpkg_deb_field () {
 extract_dpkg_deb_data () {
 	local pkg="$1"
 
-	dpkg-deb --fsys-tarfile "$pkg" | tar $EXTRACT_DEB_TAR_OPTIONS -xf - || error 1 FILEEXIST "Tried to extract package, but file already exists. Exit..."
+	dpkg-deb --fsys-tarfile "$pkg" | tar $EXTRACT_DEB_TAR_OPTIONS -xf - || error 1 FILEEXIST "Tried to extract package, but tar failed. Exit..."
 }
 
 # Raw .deb extractors
@@ -1156,7 +1159,15 @@ umount_exit_function () {
 	for dir in $UMOUNT_DIRS; do
 		realdir="$(in_target_nofail readlink -f "$dir")"
 		[ "$realdir" ] || continue
-		( cd / ; umount "$TARGET/${realdir#/}" ) || true
+		# if /proc was recursively bind-mounted, because we are running
+		# inside an unshared user namespace inside docker for example,
+		# then it cannot be recursively unmounted (even when mounted
+		# with rslave) so we do it lazily instead
+		if [ "$dir" = "/proc" ]; then
+			( cd / ; umount --lazy "$TARGET/${realdir#/}" ) || true
+		else
+			( cd / ; umount "$TARGET/${realdir#/}" ) || true
+		fi
 	done
 }
 
@@ -1189,10 +1200,9 @@ setup_proc () {
 		fi
 		;;
 	    hurd*)
-		# firmlink $TARGET/{dev,servers,proc} to the system ones.
-		settrans -a "$TARGET/dev" /hurd/firmlink /dev
-		settrans -a "$TARGET/servers" /hurd/firmlink /servers
-		settrans -a "$TARGET/proc" /hurd/firmlink /proc
+		if [ "$TARGET" != / ]; then
+			settrans -a "$TARGET/proc" /hurd/firmlink /proc
+		fi
 		;;
 	    *)
 		umount_on_exit /dev/pts
@@ -1209,7 +1219,7 @@ setup_proc () {
 		# some container environment are used at second-stage, it already treats /proc and so on
 		if [ -z "$(ls -A "$TARGET/proc")" ]; then
 			# second-stage in docker, we cannot detect it is inside docker... just ignore warning
-			in_target mount -t proc proc /proc || true
+			mount -t proc proc "$TARGET/proc" || mount -o rbind /proc "$TARGET/proc" || true
 			umount_on_exit /proc
 		fi
 		if [ -n "$(ls -A "$TARGET/sys")" ] && \
@@ -1219,7 +1229,7 @@ setup_proc () {
 				umount "$TARGET/sys" 2>/dev/null || true
 		else
 			# second-stage in docker, we cannot detect it is inside docker... just ignore warning
-			in_target mount -t sysfs sysfs /sys || true
+			mount -t sysfs sysfs "$TARGET/sys" || true
 			umount_on_exit /sys
 		fi
 		on_exit clear_mtab
@@ -1246,14 +1256,19 @@ setup_devices () {
 	    freebsd)
 		;;
 	    hurd*)
+		touch "$TARGET/servers/exec"
+		touch "$TARGET/servers/startup"
+		touch "$TARGET/dev/console"
 		;;
 	    *)
-		if [ "$CONTAINER" = "lxc" ] || [ "$CONTAINER" = "lxc-libvirt" ]; then
+		case "$CONTAINER" in
+		    (lxc | lxc-libvirt | mmdebstrap-unshare)
 			if ! setup_devices_simple; then
 				setup_devices_bind
 			fi
 			return 0
-		fi
+			;;
+		esac
 
 		setup_devices_simple
 		;;
@@ -1273,8 +1288,14 @@ setup_dynamic_devices () {
 		mount -t devfs devfs "$TARGET/dev"
 		mount -t fdescfs -o linrdlnk fdescfs "$TARGET/dev/fd" ;;
 	    hurd*)
-	        # Use the setup-translators of the hurd package
-	        in_target /usr/lib/hurd/setup-translators -k ;;
+		# Use the setup-translators of the hurd package
+		in_target /usr/lib/hurd/setup-translators -k
+		# firmlink $TARGET/{dev,servers} to the system ones.
+		if [ "$TARGET" != / ]; then
+			settrans -a "$TARGET/dev" /hurd/firmlink /dev
+			settrans -a "$TARGET/servers" /hurd/firmlink /servers
+		fi
+		;;
 	esac
 }
 
@@ -1358,17 +1379,116 @@ setup_dselect_method () {
 	esac
 }
 
-# Find out where the runtime dynamic linker and the shared libraries
-# can be installed on each architecture: native, multilib and multiarch.
-# This data can be verified by checking the files in the debian/sysdeps/
-# directory of the glibc package.
-#
-# This function must be updated to support any new architecture which
-# either installs the RTLD in a directory different from /lib or builds
-# multilib library packages.
+can_usrmerge_symlink() {
+	# Absolute symlinks can be relocated without problems.
+	test "${2#/}" = "$2" || return 0
+	while :; do
+		if test "${2#/}" != "$2"; then
+			# Handle double-slashes.
+			set -- "$1" "${2#/}"
+		elif test "${2#./}" != "$2"; then
+			# Handle ./ inside a link target.
+			set -- "$1" "${2#./}"
+		elif test "$2" = ..; then
+			# A parent directory symlink is ok if it does not
+			# cross the top level directory.
+			test "${1%/*/*}" != "$1" -a -n "${1%/*/*}"
+			return $?
+		elif test "${2#../}" != "$2"; then
+			# Symbolic link crossing / cannot be moved safely.
+			# This is prohibited by Debian Policy 10.5.
+			test "${1%/*/*}" = "$1" -o -z "${1%/*/*}" && return 1
+			set -- "${1%/*}" "${2#../}"
+		else
+			# Consider the symlink ok if its target does not
+			# contain a parent directory. When we fail here,
+			# the link target is non-minimal and doesn't happen
+			# in the archive.
+			test "${2#*/../}" = "$2"
+			return $?
+		fi
+	done
+}
+
+merge_usr_entry() {
+	local entry canon
+	canon="$TARGET/usr/${1#"$TARGET/"}"
+	test -h "$canon" &&
+		error 1 USRMERGEFAIL "cannot move %s as its destination exists as a symlink" "${1#"$TARGET"}"
+	if ! test -e "$canon"; then
+		mv "$1" "$canon"
+		return 0
+	fi
+	test -d "$1" ||
+		error 1 USRMERGEFAIL "cannot move non-directory %s as its destination exists" "${1#"$TARGET"}"
+	test -d "$canon" ||
+		error 1 USRMERGEFAIL "cannot move directory %s as its destination is not a directory" "${1#"$TARGET"}"
+	for entry in "$1/"* "$1/."*; do
+		# Some shells return . and .. on dot globs.
+		test "${entry%/.}" != "${entry%/..}" && continue
+		if test -h "$entry" && ! can_usrmerge_symlink "${entry#"$TARGET"}" "$(readlink "$entry")"; then
+			error 1 USRMERGEFAIL "cannot move relative symlink crossing top-level directory" "${entry#"$TARGET"}"
+		fi
+		# Ignore glob match failures
+		if test "${entry%'/*'}" != "${entry%'/.*'}" && ! test -e "$entry"; then
+			continue
+		fi
+		merge_usr_entry "$entry"
+	done
+	rmdir "$1"
+}
+
+merge_usr() {
+	if doing_variant buildd && [ -z "$MERGED_USR" ]; then
+	    case "$CODENAME" in
+		etch*|lenny|squeeze|wheezy|jessie*|stretch|buster|bullseye|bookworm)
+		    MERGED_USR="no"
+		    ;;
+	    esac
+	fi
+
+	if [ "$MERGED_USR" = "no" ]; then
+	    # With the usrmerge becoming pseudo-essential we need to use this flag
+	    # to ensure that even if it gets installed the buildd is not converted
+	    # when debootstrap needs to create an unmerged-usr installation.
+	    case "$CODENAME" in
+		etch*|lenny|squeeze|wheezy|jessie*|stretch|buster|bullseye)
+		    ;;
+		*)
+		    mkdir -p "$TARGET/etc"
+		    echo "this system will not be supported in the future" > "$TARGET/etc/unsupported-skip-usrmerge-conversion"
+		    if ! doing_variant buildd; then
+			warning SANITYCHECK "Upgrading non-merged-/usr environments post-bookworm is unsupported. Only do this for CI/QA infrastructure that will be re-bootstrapped rather than upgraded."
+		    fi
+		    ;;
+	    esac
+	    return 0;
+	fi
+
+	local dir
+	# This is list includes all possible multilib directories. It must be
+	# updated when new multilib directories are being added. Hopefully,
+	# all new architectures use multiarch instead, so we never get to
+	# update this.
+	for dir in bin lib lib32 lib64 libo32 libx32 sbin; do
+		test -h "$TARGET/$dir" && continue
+		test -e "$TARGET/$dir" || continue
+		merge_usr_entry "$TARGET/$dir"
+		ln -s "usr/$dir" "$TARGET/$dir"
+	done
+}
+
+# Previous implementation of merged /usr: not used within debootstrap,
+# but used by mmdebstrap's hooks/merged-usr/setup00.sh, mainly to get
+# the correct per-architecture $link_dir list of non-default multilib
+# directories.
 setup_merged_usr() {
 	if doing_variant buildd && [ -z "$MERGED_USR" ]; then
-		MERGED_USR="no"
+	    case "$CODENAME" in
+		etch*|lenny|squeeze|wheezy|jessie*|stretch|buster|bullseye|bookworm)
+		    MERGED_USR="no"
+		    ;;
+	    esac
 	fi
 
 	if [ "$MERGED_USR" = "no" ]; then
@@ -1549,7 +1669,7 @@ while (<STDIN>) {
 			local m="$3"
 			local p="$4"
 			shift; shift; shift; shift
-			LC_ALL=C grep "$gropt" '^$|^Package:|^Priority:' "$p" | pkgdetails_field 0 "$f" "$m" "$@"
+			LC_ALL=C grep "$gropt" '^$|^Package:|^Priority:|^Essential:' "$p" | pkgdetails_field 0 "$f" "$m" "$@"
 		elif [ "$1" = "STANZAS" ]; then
 			local pkgdest="$2"; shift; shift
 			perl -e '
@@ -1591,7 +1711,7 @@ resolve_deps () {
 	while [ "$PKGS" != "" ]; do
 		local NEWPKGS=""
 		for s in $SUITE $EXTRA_SUITES; do
-			for c in ${COMPONENTS:-$(echo ${USE_COMPONENTS} | tr '|' ' ')}; do
+			for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
 				local path="dists/$s/$c/binary-$ARCH/Packages"
 				local pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$ARCH" "$m1" "$path")"
 				NEWPKGS="$NEWPKGS $("$PKGDETAILS" GETDEPS "$pkgdest" $PKGS)"
@@ -1603,7 +1723,7 @@ resolve_deps () {
 		PKGS=$(echo "$PKGS $NEWPKGS" | tr ' ' '\n' | sort | uniq)
 		local REALPKGS=""
 		for s in $SUITE $EXTRA_SUITES; do
-			for c in ${COMPONENTS:-$(echo ${USE_COMPONENTS} | tr '|' ' ')}; do
+			for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
 				local path="dists/$s/$c/binary-$ARCH/Packages"
 				local pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$ARCH" "$m1" "$path")"
 				REALPKGS="$REALPKGS $("$PKGDETAILS" PKGS REAL "$pkgdest" $PKGS | sed -n 's/ .*REAL.*$//p')"
@@ -1622,7 +1742,7 @@ setup_available () {
 	m1="${MIRRORS%% *}"
 
 	for s in $SUITE $EXTRA_SUITES; do
-		for c in ${COMPONENTS:-$(echo ${USE_COMPONENTS} | tr '|' ' ')}; do
+		for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
 			path="dists/$s/$c/binary-$ARCH/Packages"
 			pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$ARCH" "$m1" "$path")"
 			# XXX: What if a package is in more than one component?
@@ -1658,7 +1778,7 @@ check_sane_mount () {
 	    *)
 		if ! doing_variant fakechroot; then
 		case "$CONTAINER" in
-		  lxc|lxc-libvirt)
+		  lxc|lxc-libvirt|mmdebstrap-unshare)
 		    ;;
 		  *)
 		    mknod "$1/test-dev-null" c 1 3 || return 1
